### ISSUE TITLE
AssertionError after upgrading to pip 19.0

### ISSUE THREAD

**Issue by BasNijhuis** [testing-cabal/linecache2#16]
~~~python
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/usr/lib/python3.6/site-packages/pip/_internal/wheel.py", line 848, in build
    assert building_is_possible
AssertionError
~~~

**Comment by rbtcollins** [comment]
This looks to be a pip 19 issue, not linecache.
